application_name: dot-net-auth
build_namespace: "{{ application_name }}-build"
dev_namespace: "{{ application_name }}-dev"
application_repository_url: "https://github.com/cloudfirst-dev/dotnet-core-jwt.git"
application_repository_ref: master
application_readiness_response: "html"
application_readiness_path: "/"
pipeline_script: "Jenkinsfile"

openshift_cluster_content:
- object: projects
  content:
  - name: "create environments"
    template: "{{ inventory_dir }}/../.openshift/projects/projects.yml"
    action: create
    params_from_vars:
      BUILD_NAMESPACE: "{{ build_namespace }}"
      DEV_NAMESPACE: "{{ dev_namespace }}"
    tags:
      - project
- object: builds
  content:
  - name: "deploy build pipeline to dev"
    template: "{{ inventory_dir }}/../.openshift/templates/build.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ application_name }}"
      NAMESPACE: "{{ build_namespace }}"
      SOURCE_REPOSITORY_URL: "{{ application_repository_url }}"
      SOURCE_REPOSITORY_REF: "{{ application_repository_ref }}"
      PIPELINE_SCRIPT: "{{ pipeline_script }}"
    tags:
      - build
- object: roles
  content:
  - name: "deploy the RBAC controls"
    template: "{{ inventory_dir }}/../.openshift/templates/roles.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ application_name }}"
- object: deployments
  content:
  - name: "deploy dev environment"
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ application_name }}"
      NAMESPACE: "{{ dev_namespace }}"
      READINESS_RESPONSE: "{{ application_readiness_response }}"
      READINESS_PATH: "{{ application_readiness_path }}"
      TOKENS_AUDIENCE: "{{ tokens_audience }}"
      TOKENS_ISSUER: "{{ tokens_issuer }}"
    tags:
      - deployment
  - name: "deploy config maps"
    template: "{{ inventory_dir }}/../.openshift/templates/config.yml"
    params_from_vars:
      NAMESPACE: "{{ dev_namespace }}"
      AUTH_URL: "{{ auth_url }}"
      BASE_API_URL: "{{ base_api_url }}"
      AUTH_CLIENT_ID: "{{ auth_client_id }}"
      AUTH_PUBLIC_KEY: "{{ auth_public_key }}"
    tags:
      - deployment