apiVersion: v1
kind: Template
labels:
  template: generic-dotnet-jenkins-pipeline
metadata:
  annotations:
    description: Application template for .NET Core applications built using a Jenkins Pipeline
    iconClass: icon-tomcat
    version: 1.2.0
  name: generic-dotnet-jenkins-pipeline
objects:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: ${BUILD_NAMESPACE}
    creationTimestam: null
  displayName: .NET Jobs App - Build
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: ${DEV_NAMESPACE}
    creationTimestam: null
  displayName: .NET Jobs App - Dev
parameters:
- description: The name for the build namespace.
  name: BUILD_NAMESPACE
  required: true
- description: The name for the dev namespace
  name: DEV_NAMESPACE
  required: true