apiVersion: v1
kind: Template
labels:
  template: basic-dotnet-core
metadata:
  annotations:
    description: Application template for .NET Core applications built using a Jenkins Pipeline
    iconClass: icon-tomcat
    version: 1.2.0
  name: basic-dotnet-core
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      app: ${APPLICATION_NAME}-web
    name: ${APPLICATION_NAME}-web
    namespace: ${NAMESPACE}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      app: ${APPLICATION_NAME}-web
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}-web
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      app: ${APPLICATION_NAME}-ui
    name: ${APPLICATION_NAME}-ui
    namespace: ${NAMESPACE}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}-ui
- apiVersion: v1
  id: ${APPLICATION_NAME}-ui
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ui
    namespace: ${NAMESPACE}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}-ui
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ui
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TOKENS_ISSUER
            value: ${TOKENS_ISSUER}
          - name: TOKENS_AUDIENCE
            value: ${TOKENS_AUDIENCE}
          - name: ALLOWED_ORIGIN
            value: ${ALLOWED_ORIGIN}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl -s 'http://localhost:8080${READINESS_PATH}'
          volumeMounts:
          # name must match the volume name below
          - name: public-key
            mountPath: /certs
            readOnly: true
        volumes:
        - name: public-key
          secret:
            secretName: public-key
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ui
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}-ui
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}-ui
        name: ${APPLICATION_NAME}-ui
      spec:
        volumes:
        - name: ui-config
          configMap:
            name: ui-config
            defaultMode: 420
        containers:
        - image: ${APPLICATION_NAME}-ui
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}-ui
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl -s 'http://localhost:8080${READINESS_PATH}'
          volumeMounts:
          - name: ui-config
            mountPath: /opt/app-root/src/config
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}-ui
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}-ui:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: basic-dotnet-core
- description: The namespace to deploy into
  name: NAMESPACE
  required: true
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
- description: 'URI to check for app health'
  name: READINESS_PATH
  required: true
  value: '/'
- description: 'OAuth Token Issuer for validation'
  name: TOKENS_ISSUER
  required: true
- description: 'OAuth Token Audience for validation'
  name: TOKENS_AUDIENCE
  required: true
- description: "Allowed origins for api"
  name: ALLOWED_ORIGIN
  value: "*"
  required: true