apiVersion: v1
kind: Template
labels:
  template: basic-dotnet-core
metadata:
  annotations:
    description: Application template for .NET Core applications built using a Jenkins Pipeline
    iconClass: icon-tomcat
    version: 1.2.0
  name: basic-dotnet-core
objects:
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: jenkins-admin
    namespace: ${APPLICATION_NAME}-dev
  subjects:
    - kind: ServiceAccount
      name: jenkins
      namespace: ${APPLICATION_NAME}-build
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true