name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jacobsee/s2i-github-action@master
      with:
        path: api
        base: registry.centos.org/dotnet/dotnet-31-centos7
        output_image: quay.io/cloudfirst/dotnet-core-jwt-api:latest
        image_push_registry: quay.io
        image_push_username: ${{ secrets.DOCKER_USERNAME }}
        image_push_password: ${{ secrets.DOCKER_PASSWORD }}
