name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: vrutkovs/action-s2i@master
      with:
        path: api
        base: registry.centos.org/dotnet/dotnet-31-centos7
        image: quay.io/cloudfirst/dotnet-core-jwt-api:latest
