name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: --cwd ui install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: --cwd ui build # will run `yarn build` command
